//! Scan vulnerability PDF report — port of `reports/pdf-generator.ts`.
//!
//! Generates a professional PDF with: cover page, table of contents,
//! executive summary (severity breakdown + risk assessment),
//! vulnerability details (sorted by severity), and appendix (tool log).

use crate::models::{Agent, Scan, Severity, ToolExecution, Vulnerability};
use super::pdf_writer::{format_date, hex_to_rgb, PdfWriter};

/// Severity → display color (hex).
fn severity_color(sev: &Severity) -> &'static str {
    match sev {
        Severity::Critical => "#FF0000",
        Severity::High => "#FF6B00",
        Severity::Medium => "#FFB800",
        Severity::Low => "#00A8FF",
        Severity::Info => "#6B6B6B",
    }
}

const COLOR_TEXT: &str = "#FFFFFF";
const COLOR_MUTED: &str = "#A0A0A0";
const COLOR_ACCENT: &str = "#22C55E";

/// Generate a PDF report for a completed scan.
pub fn generate_scan_pdf(
    scan: &Scan,
    vulnerabilities: &[Vulnerability],
    agents: &[Agent],
    tools: &[ToolExecution],
) -> Vec<u8> {
    let mut pdf = PdfWriter::new(&format!("Strix Security Report - {}", scan.target));

    // Sort vulnerabilities by severity (critical first)
    let mut sorted: Vec<&Vulnerability> = vulnerabilities.iter().collect();
    sorted.sort_by(|a, b| a.severity.cmp(&b.severity));

    // ════════════════════ Cover Page ════════════════════

    pdf.font_regular(10.0);
    pdf.color_hex(COLOR_MUTED);
    pdf.move_down(5.0);
    pdf.text_centered("CONFIDENTIAL");
    pdf.move_down(25.0);

    pdf.font_bold(28.0);
    pdf.color_hex(COLOR_TEXT);
    pdf.text_centered("Security Assessment Report");
    pdf.move_down(5.0);

    pdf.font_regular(16.0);
    pdf.color_hex(COLOR_ACCENT);
    pdf.text_centered(&scan.target);
    pdf.move_down(15.0);

    pdf.font_regular(11.0);
    pdf.color_hex(COLOR_MUTED);
    pdf.text_centered(&format!("Date: {}", format_date(&scan.created_at)));
    pdf.text_centered(&format!("Scan ID: {}", scan.id));
    pdf.text_centered(&format!("Mode: {}", scan.mode));
    pdf.text_centered(&format!("Target Type: {}", scan.target_type.as_str()));

    if let (Some(ref started), Some(ref completed)) = (&scan.started_at, &scan.completed_at) {
        if let (Ok(s), Ok(c)) = (
            chrono::DateTime::parse_from_rfc3339(started),
            chrono::DateTime::parse_from_rfc3339(completed),
        ) {
            let dur = c.signed_duration_since(s);
            let mins = dur.num_minutes();
            let secs = dur.num_seconds() % 60;
            pdf.text_centered(&format!("Duration: {}m {}s", mins, secs));
        }
    }

    pdf.move_down(25.0);
    pdf.font_regular(10.0);
    pdf.color_hex(COLOR_MUTED);
    pdf.text_centered("Generated by Strix - AI-Powered Security Testing Framework");

    // ════════════════════ Table of Contents ════════════════════

    pdf.new_page();
    pdf.font_bold(20.0);
    pdf.color_hex(COLOR_TEXT);
    pdf.text("Table of Contents");
    pdf.move_down(5.0);

    pdf.font_regular(12.0);
    pdf.color_hex(COLOR_MUTED);
    pdf.text("1. Executive Summary ..................................... 3");
    pdf.text("2. Vulnerability Details .................................. 4");
    for (i, v) in sorted.iter().enumerate() {
        pdf.text(&format!(
            "   {}. {} ({})",
            i + 1,
            v.title,
            v.severity.as_str().to_uppercase()
        ));
    }
    pdf.text(&format!(
        "3. Appendix - Tool Execution Log .............. {}",
        4 + sorted.len()
    ));

    // ════════════════════ Executive Summary ════════════════════

    pdf.new_page();
    pdf.font_bold(20.0);
    pdf.color_hex(COLOR_TEXT);
    pdf.text("1. Executive Summary");
    pdf.move_down(5.0);

    // Severity counts
    let mut counts = [0u32; 5]; // critical, high, medium, low, info
    for v in &sorted {
        match v.severity {
            Severity::Critical => counts[0] += 1,
            Severity::High => counts[1] += 1,
            Severity::Medium => counts[2] += 1,
            Severity::Low => counts[3] += 1,
            Severity::Info => counts[4] += 1,
        }
    }

    pdf.font_bold(14.0);
    pdf.color_hex(COLOR_TEXT);
    pdf.text("Findings Overview");
    pdf.move_down(2.0);

    pdf.font_regular(11.0);
    pdf.color_hex(COLOR_MUTED);
    pdf.text(&format!("Total Findings: {}", sorted.len()));
    pdf.text(&format!("Agents Deployed: {}", agents.len()));
    pdf.text(&format!("Tool Executions: {}", tools.len()));
    pdf.move_down(5.0);

    // Severity breakdown with bars
    let sev_labels = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];
    let sev_colors = [
        Severity::Critical,
        Severity::High,
        Severity::Medium,
        Severity::Low,
        Severity::Info,
    ];
    let max_count = sorted.len().max(1) as f64;

    for (i, (label, sev)) in sev_labels.iter().zip(sev_colors.iter()).enumerate() {
        let count = counts[i];
        let color = severity_color(sev);
        let (r, g, b) = hex_to_rgb(color);

        pdf.font_regular(10.0);
        pdf.color(r, g, b);
        pdf.text(&format!("{}: {}", label, count));

        if count > 0 {
            let bar_w = (count as f64 / max_count) * 100.0; // max 100mm
            let bar_w = bar_w.min(100.0).max(5.0);
            pdf.filled_rect(MARGIN_MM, bar_w, 2.5, r, g, b);
            pdf.move_down(4.0);
        }
    }

    pdf.move_down(5.0);

    // Risk assessment
    pdf.font_bold(14.0);
    pdf.color_hex(COLOR_TEXT);
    pdf.text("Risk Assessment");
    pdf.move_down(2.0);

    let risk_level = if counts[0] > 0 {
        "Critical"
    } else if counts[1] > 0 {
        "High"
    } else if counts[2] > 0 {
        "Medium"
    } else {
        "Low"
    };

    pdf.font_regular(11.0);
    pdf.color_hex(COLOR_MUTED);
    pdf.text(&format!("Overall Risk Level: {}", risk_level));
    pdf.move_down(2.0);

    if counts[0] > 0 {
        pdf.color_hex("#FF0000");
        pdf.text(&format!(
            "CRITICAL: {} critical vulnerabilities require immediate remediation.",
            counts[0]
        ));
    }
    if counts[1] > 0 {
        pdf.color_hex("#FF6B00");
        pdf.text(&format!(
            "HIGH: {} high-severity issues should be addressed in the next sprint.",
            counts[1]
        ));
    }

    // ════════════════════ Vulnerability Details ════════════════════

    pdf.new_page();
    pdf.font_bold(20.0);
    pdf.color_hex(COLOR_TEXT);
    pdf.text("2. Vulnerability Details");
    pdf.move_down(5.0);

    if sorted.is_empty() {
        pdf.font_regular(12.0);
        pdf.color_hex(COLOR_ACCENT);
        pdf.text("No vulnerabilities were found during this assessment.");
    }

    for (i, v) in sorted.iter().enumerate() {
        pdf.ensure_space(60.0);

        // Title
        pdf.font_bold(14.0);
        pdf.color_hex(COLOR_TEXT);
        pdf.text(&format!("{}. {}", i + 1, v.title));

        // Severity badge
        pdf.font_regular(10.0);
        let (r, g, b) = hex_to_rgb(severity_color(&v.severity));
        pdf.color(r, g, b);
        pdf.text(&v.severity.as_str().to_uppercase());

        if let Some(cvss) = v.cvss {
            pdf.color_hex(COLOR_MUTED);
            pdf.text(&format!("CVSS: {:.1}", cvss));
        }
        pdf.move_down(2.0);

        // Affected URL
        if let Some(ref url) = v.affected_url {
            pdf.font_regular(10.0);
            pdf.color_hex(COLOR_MUTED);
            pdf.text("Affected URL:");
            pdf.color_hex(COLOR_ACCENT);
            pdf.text(url);
            pdf.move_down(1.0);
        }

        // Description
        if !v.description.is_empty() {
            pdf.font_regular(10.0);
            pdf.color_hex(COLOR_MUTED);
            pdf.text("Description:");
            pdf.color_hex(COLOR_TEXT);
            pdf.text(&v.description);
            pdf.move_down(1.0);
        }

        // Proof of Concept
        if let Some(ref poc) = v.proof_of_concept {
            pdf.font_regular(10.0);
            pdf.color_hex(COLOR_MUTED);
            pdf.text("Proof of Concept:");
            pdf.font_mono(9.0);
            pdf.color_hex(COLOR_TEXT);
            pdf.text(poc);
            pdf.move_down(1.0);
        }

        // Impact
        if let Some(ref impact) = v.impact {
            pdf.font_regular(10.0);
            pdf.color_hex(COLOR_MUTED);
            pdf.text("Impact:");
            pdf.color_hex(COLOR_TEXT);
            pdf.text(impact);
            pdf.move_down(1.0);
        }

        // Remediation
        if let Some(ref rem) = v.remediation {
            pdf.font_regular(10.0);
            pdf.color_hex(COLOR_MUTED);
            pdf.text("Remediation:");
            pdf.color_hex(COLOR_ACCENT);
            pdf.text(rem);
            pdf.move_down(1.0);
        }

        // References
        if let Some(ref refs) = v.references {
            if !refs.is_empty() {
                pdf.font_regular(10.0);
                pdf.color_hex(COLOR_MUTED);
                pdf.text("References:");
                pdf.color_hex(COLOR_ACCENT);
                for r in refs {
                    pdf.text(&format!("  - {}", r));
                }
            }
        }

        // Separator
        pdf.move_down(2.0);
        pdf.horizontal_line();
        pdf.move_down(5.0);
    }

    // ════════════════════ Appendix ════════════════════

    pdf.new_page();
    pdf.font_bold(20.0);
    pdf.color_hex(COLOR_TEXT);
    pdf.text("3. Appendix - Tool Execution Log");
    pdf.move_down(5.0);

    pdf.font_mono(9.0);
    pdf.color_hex(COLOR_MUTED);

    for tool in tools.iter().take(100) {
        pdf.ensure_space(5.0);

        let duration = tool
            .duration
            .map(|d| format!("{:.1}s", d / 1000.0))
            .unwrap_or_else(|| "...".into());
        let status = if tool.status.as_str() == "completed" {
            "OK"
        } else {
            tool.status.as_str()
        };

        let time_str = format_date(&tool.started_at);
        pdf.text(&format!(
            "[{}] {} ({}, {})",
            time_str, tool.tool_name, status, duration
        ));
    }

    if tools.len() > 100 {
        pdf.move_down(2.0);
        pdf.text(&format!("... and {} more tool executions", tools.len() - 100));
    }

    pdf.finish()
}

/// Left margin constant used for severity bar positioning.
const MARGIN_MM: f64 = 20.0;
