import PDFDocument from "pdfkit";
import type { Scan, Vulnerability, Agent, ToolExecution } from "@strix-webui/shared";

const COLORS = {
  bg: "#0A0A0A",
  text: "#FFFFFF",
  muted: "#A0A0A0",
  border: "#2A2A2A",
  critical: "#FF0000",
  high: "#FF6B00",
  medium: "#FFB800",
  low: "#00A8FF",
  info: "#6B6B6B",
  accent: "#22C55E",
};

function severityColor(severity: string): string {
  return COLORS[severity as keyof typeof COLORS] || COLORS.muted;
}

function severityScore(severity: string): number {
  const scores: Record<string, number> = { critical: 5, high: 4, medium: 3, low: 2, info: 1 };
  return scores[severity] || 0;
}

export async function generatePDFReport(
  scan: Scan,
  vulnerabilities: Vulnerability[],
  agents: Agent[],
  tools: ToolExecution[]
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: {
        Title: `Strix Security Report - ${scan.target}`,
        Author: "Strix Security Scanner",
        Subject: "Penetration Testing Report",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 120; // margins

    // Sort vulns by severity
    const sorted = [...vulnerabilities].sort((a, b) => severityScore(b.severity) - severityScore(a.severity));

    // ==================== Cover Page ====================
    doc.fontSize(10).fillColor(COLORS.muted).text("CONFIDENTIAL", { align: "center" });
    doc.moveDown(6);
    doc.fontSize(32).fillColor(COLORS.text).text("Security Assessment Report", { align: "center" });
    doc.moveDown(1);
    doc.fontSize(16).fillColor(COLORS.accent).text(scan.target, { align: "center" });
    doc.moveDown(3);

    doc.fontSize(11).fillColor(COLORS.muted);
    doc.text(`Date: ${new Date(scan.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, { align: "center" });
    doc.text(`Scan ID: ${scan.id}`, { align: "center" });
    doc.text(`Mode: ${scan.mode}`, { align: "center" });
    doc.text(`Target Type: ${scan.targetType}`, { align: "center" });

    if (scan.startedAt && scan.completedAt) {
      const durationMs = new Date(scan.completedAt).getTime() - new Date(scan.startedAt).getTime();
      const mins = Math.floor(durationMs / 60000);
      const secs = Math.floor((durationMs % 60000) / 1000);
      doc.text(`Duration: ${mins}m ${secs}s`, { align: "center" });
    }

    doc.moveDown(6);
    doc.fontSize(10).fillColor(COLORS.muted).text("Generated by Strix - AI-Powered Security Testing Framework", { align: "center" });

    // ==================== Table of Contents ====================
    doc.addPage();
    doc.fontSize(20).fillColor(COLORS.text).text("Table of Contents");
    doc.moveDown(1);

    doc.fontSize(12).fillColor(COLORS.muted);
    doc.text("1. Executive Summary ..................................... 3");
    doc.text("2. Vulnerability Details .................................. 4");
    sorted.forEach((v, i) => {
      doc.text(`   ${i + 1}. ${v.title} (${v.severity.toUpperCase()})`);
    });
    doc.text(`3. Appendix - Tool Execution Log .............. ${4 + sorted.length}`);

    // ==================== Executive Summary ====================
    doc.addPage();
    doc.fontSize(20).fillColor(COLORS.text).text("1. Executive Summary");
    doc.moveDown(1);

    // Severity breakdown
    const severityCounts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
    for (const v of sorted) severityCounts[v.severity]++;

    doc.fontSize(14).fillColor(COLORS.text).text("Findings Overview");
    doc.moveDown(0.5);

    doc.fontSize(11).fillColor(COLORS.muted);
    doc.text(`Total Findings: ${sorted.length}`);
    doc.text(`Agents Deployed: ${agents.length}`);
    doc.text(`Tool Executions: ${tools.length}`);
    doc.moveDown(1);

    // Severity bars
    const severities = ["critical", "high", "medium", "low", "info"] as const;
    for (const sev of severities) {
      const count = severityCounts[sev];
      const color = severityColor(sev);

      doc.fontSize(10).fillColor(color).text(`${sev.toUpperCase()}: ${count}`, {
        continued: false,
      });

      if (count > 0) {
        const barWidth = Math.min((count / Math.max(sorted.length, 1)) * pageWidth * 0.6, pageWidth * 0.6);
        doc.rect(doc.x, doc.y, barWidth, 8).fill(color);
        doc.moveDown(0.8);
      }
    }

    doc.moveDown(1);

    // Risk assessment
    doc.fontSize(14).fillColor(COLORS.text).text("Risk Assessment");
    doc.moveDown(0.5);

    let riskLevel = "Low";
    if (severityCounts.critical > 0) riskLevel = "Critical";
    else if (severityCounts.high > 0) riskLevel = "High";
    else if (severityCounts.medium > 0) riskLevel = "Medium";

    doc.fontSize(11).fillColor(COLORS.muted);
    doc.text(`Overall Risk Level: ${riskLevel}`);
    doc.moveDown(0.5);

    if (severityCounts.critical > 0) {
      doc.fillColor(COLORS.critical).text(
        `CRITICAL: ${severityCounts.critical} critical vulnerabilities require immediate remediation.`
      );
    }
    if (severityCounts.high > 0) {
      doc.fillColor(COLORS.high).text(
        `HIGH: ${severityCounts.high} high-severity issues should be addressed in the next sprint.`
      );
    }

    // ==================== Vulnerability Details ====================
    doc.addPage();
    doc.fontSize(20).fillColor(COLORS.text).text("2. Vulnerability Details");
    doc.moveDown(1);

    for (let i = 0; i < sorted.length; i++) {
      const v = sorted[i];

      // Check if we need a new page
      if (doc.y > doc.page.height - 200) {
        doc.addPage();
      }

      // Vulnerability header
      doc.fontSize(14).fillColor(COLORS.text).text(`${i + 1}. ${v.title}`);

      // Severity badge
      doc.fontSize(10).fillColor(severityColor(v.severity)).text(v.severity.toUpperCase());

      if (v.cvss) {
        doc.fillColor(COLORS.muted).text(`CVSS: ${v.cvss}`, { continued: false });
      }

      doc.moveDown(0.5);

      // Affected URL
      if (v.affectedUrl) {
        doc.fontSize(10).fillColor(COLORS.muted).text("Affected URL:");
        doc.fillColor(COLORS.accent).text(v.affectedUrl);
        doc.moveDown(0.3);
      }

      // Description
      if (v.description) {
        doc.fontSize(10).fillColor(COLORS.muted).text("Description:");
        doc.fillColor(COLORS.text).fontSize(10).text(v.description, { width: pageWidth });
        doc.moveDown(0.3);
      }

      // Proof of Concept
      if (v.proofOfConcept) {
        doc.fontSize(10).fillColor(COLORS.muted).text("Proof of Concept:");
        doc.font("Courier").fontSize(9).fillColor(COLORS.text).text(v.proofOfConcept, { width: pageWidth });
        doc.font("Helvetica");
        doc.moveDown(0.3);
      }

      // Impact
      if (v.impact) {
        doc.fontSize(10).fillColor(COLORS.muted).text("Impact:");
        doc.fillColor(COLORS.text).fontSize(10).text(v.impact, { width: pageWidth });
        doc.moveDown(0.3);
      }

      // Remediation
      if (v.remediation) {
        doc.fontSize(10).fillColor(COLORS.muted).text("Remediation:");
        doc.fillColor(COLORS.accent).fontSize(10).text(v.remediation, { width: pageWidth });
        doc.moveDown(0.3);
      }

      // References
      if (v.references && v.references.length > 0) {
        doc.fontSize(10).fillColor(COLORS.muted).text("References:");
        for (const ref of v.references) {
          doc.fillColor(COLORS.accent).text(`  - ${ref}`);
        }
      }

      // Separator
      doc.moveDown(0.5);
      doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).stroke(COLORS.border);
      doc.moveDown(1);
    }

    if (sorted.length === 0) {
      doc.fontSize(12).fillColor(COLORS.accent).text("No vulnerabilities were found during this assessment.");
    }

    // ==================== Appendix ====================
    doc.addPage();
    doc.fontSize(20).fillColor(COLORS.text).text("3. Appendix - Tool Execution Log");
    doc.moveDown(1);

    doc.fontSize(9).fillColor(COLORS.muted);
    for (const tool of tools.slice(0, 100)) {
      if (doc.y > doc.page.height - 80) {
        doc.addPage();
        doc.fontSize(9).fillColor(COLORS.muted);
      }

      const duration = tool.duration ? `${(tool.duration / 1000).toFixed(1)}s` : "...";
      const status = tool.status === "completed" ? "OK" : tool.status.toUpperCase();
      doc.text(
        `[${new Date(tool.startedAt).toLocaleTimeString()}] ${tool.toolName} (${status}, ${duration})`,
        { width: pageWidth }
      );
    }

    if (tools.length > 100) {
      doc.moveDown(0.5);
      doc.text(`... and ${tools.length - 100} more tool executions`);
    }

    doc.end();
  });
}
